import { ResearchExpertise } from '@/components/research-expertise';
import { EnglishFrame, EnglishCollaboration } from '@/components/english-site';
import { themesEn } from '@/lib/english-content';
import { researchPublications } from '@/lib/works';
export const metadata = { title: 'Research | Suga Group', description: 'Molecular exploration through structural transformations, synthesis of π-conjugated molecules, and polymer structure–property relationships. Explore our research and opportunities for collaboration.' };
export default function Page() {
  return <EnglishFrame title="Research" section="research"><header className="research-introduction"><p className="research-eyebrow">RESEARCH / SUGA GROUP</p><h1>Exploring unseen molecules.<br />Rethinking molecular possibilities.</h1><div className="research-introduction-body"><p>What properties might lie hidden in molecules that have not yet been made? And what characteristics and advantages do familiar molecules have compared with other molecules that could exist?</p><p>By exploring a wide range of molecular structures and properties, we identify molecules with new properties and functions while reassessing familiar molecules within a broader chemical space. Discovering unknown molecules and understanding known ones are complementary ways to investigate the relationship between structure, properties, and function.</p></div></header><div className="research-reading-layout"><nav className="research-contents" aria-label="Research themes"><p>RESEARCH THEMES</p>{themesEn.map(t => <a href={`#${t.id}`} key={t.id}><span>{t.number}</span>{t.title}</a>)}<a href="#other-research" className="research-contents-contact">Other research <span aria-hidden="true">↘</span></a></nav><div className="research-articles">{themesEn.map(t => <section className="research-article" id={t.id} key={t.id}><div className="research-topic-label"><span>{t.number}</span><small>{t.english}</small></div><h2>{t.title}</h2><p className="research-article-copy">{t.copy}</p><p>{t.introduction}</p>{t.sections.map((s, i) => <div className="research-subsection" key={i}>{'title' in s && <h3>{s.title}</h3>}{s.paragraphs.map(p => <p key={p}>{p}</p>)}</div>)}{researchPublications(t.id).map(p => <aside className="research-paper" key={p.id}><p className="research-eyebrow">RELATED PUBLICATION</p><a href={`https://doi.org/${p.doi}`}>{p.title} ↗</a><p>{p.journal} · {p.year}</p><span>DOI: {p.doi}</span></aside>)}</section>)}<ResearchExpertise english /></div></div><EnglishCollaboration id="research-collaboration" compact /></EnglishFrame>;
}
export function generateStaticParams() { return [{ lang: 'en' }]; }
