import { SelectedPublications } from '@/components/selected-publications';
import { GroupPeople } from '@/components/group-people';
import { GroupHeader } from '@/components/group-header';
import { StudentGuide } from '@/components/student-guide';
import { GroupContact } from '@/components/group-contact';
import { GroupNews } from '@/components/group-news';
import { CollaborationGuide } from '@/components/collaboration-guide';
import { ResearchOverview } from '@/components/research-overview';
import { groupIntroduction } from '@/lib/research-content';
import { ChemicalVoyage } from '@/components/chemical-voyage';
import { studies, type StudySlug } from '@/lib/design-studies';
const menu = [['research','研究内容'],['people','メンバー'],['works','論文・業績'],['join','学生の皆さんへ'],['collaborate','共同研究']] as const;
const topics = [
 {id:'01',en:'CHEMICAL SPACE',title:'化学空間と分子探索',body:'広大な分子の可能性の中から、どのように有望な構造を見つけるか。計算化学・量子化学の視点から、分子探索の方法を考えます。',tags:'化学空間 / 分子探索 / 計算化学'},
 {id:'02',en:'FUNDAMENTAL ORGANIC CHEMISTRY',title:'分子の構造と反応性',body:'分子の構造は、性質や反応のしやすさとどう結びつくのか。基礎有機化学の問いを、電子状態から理解することを目指します。',tags:'基礎有機化学 / 量子化学 / 電子状態'},
 {id:'03',en:'POLYMER SCIENCE',title:'分子から、高分子へ',body:'繰り返す構造が、どのような性質を生むのか。有機化学と高分子科学をつなぎ、構造と性質の関係を探ります。',tags:'高分子科学 / 分子構造 / 構造と物性'},
];
function SpaceMap({compact=false}:{compact?:boolean}){return <svg viewBox="0 0 500 310" role="img" aria-label="化学空間で探索対象を絞り込む概念図。実際の計算結果ではありません。" className={compact?'space-map compact':'space-map'}><g stroke="currentColor" opacity=".13" fill="none"><path d="M40 35V270H470"/>{[90,140,190,240,290,340,390,440].map(x=><path key={x} d={`M${x} 35V270`}/>)}{[70,110,150,190,230].map(y=><path key={y} d={`M40 ${y}H470`}/>)}</g><g fill="currentColor" opacity=".35">{Array.from({length:66},(_,i)=>{const x=65+((i*79)%383),y=51+((i*43+i*i*7)%198);return <circle key={i} cx={x} cy={y} r={i%4===0?3:2}/>})}</g><g fill="none" stroke="currentColor"><ellipse cx="322" cy="131" rx="73" ry="50" strokeDasharray="4 5" opacity=".5"/><path d="M127 216L217 185L285 141L333 117" strokeWidth="2"/></g><g fill="currentColor">{[[127,216],[217,185],[285,141],[333,117]].map(([x,y])=><circle key={x} cx={x} cy={y} r="5"/>)}</g><g fontFamily="Arial,sans-serif" fontSize="10" fill="currentColor"><text x="51" y="23">CHEMICAL SPACE</text><text x="344" y="103">TARGET REGION</text><text x="44" y="295">分子の可能性を、探索する。</text><text x="353" y="295">CONCEPTUAL MAP</text></g></svg>}
function Molecule({polymer=false}:{polymer?:boolean}){return <svg viewBox="0 0 350 180" className="molecule-diagram" role="img" aria-label={polymer?'高分子の繰り返し構造の模式図':'ベンゼンの構造式を用いた有機化学のイメージ'}><g fill="none" stroke="currentColor" strokeWidth="2">{polymer?<><path d="M65 107L105 83L145 107L185 83L225 107L265 83"/><path d="M85 55H75V135H85M245 55H255V135H245"/></>:<><path d="M140 40L184 65V115L140 140L96 115V65Z"/><path d="M141 49L176 70M176 110L141 131M104 109V71"/></>}</g><text x={polymer?269:212} y={polymer?143:96} fill="currentColor" fontSize="17" fontFamily="Georgia,serif">{polymer?'n':'C₆H₆'}</text><text x="175" y="169" textAnchor="middle" fill="currentColor" fontSize="9" fontFamily="Arial,sans-serif">{polymer?'REPEATING STRUCTURE · SCHEMATIC':'STRUCTURE / ELECTRONIC STATE / REACTIVITY'}</text></svg>}
function Research({selected=false}:{selected?:boolean}){return selected?<ResearchOverview/>:<LegacyResearch/>}
function LegacyResearch(){return <section id="research" className="ds-section ds-research"><div className="ds-section-head"><p>01 / RESEARCH</p><h2>研究の問い</h2><span>分子の可能性を、基礎から考える。</span></div><div className="ds-topic-grid">{topics.map((t,i)=><article className="ds-topic" key={t.id}><div className="ds-topic-visual">{i===0?<SpaceMap compact/>:<Molecule polymer={i===2}/>}</div><div className="ds-topic-text"><span className="ds-topic-id">{t.id} <small>{t.en}</small></span><h3>{t.title}</h3><p>{t.body}</p><details><summary>研究の視点 <span>＋</span></summary><p>{t.tags}を軸に研究課題を具体化していきます。個別のテーマや進行中のプロジェクトは、確定後に紹介します。</p></details><div className="ds-tags">{t.tags}</div></div></article>)}</div></section>}
function People({selected=false}:{selected?:boolean}){return selected?<GroupPeople/>:<LegacyPeople/>}
function LegacyPeople(){return <section id="people" className="ds-section ds-people"><div className="ds-section-head"><p>02 / PEOPLE</p><h2>須賀グループの人たち</h2><span>研究室の立ち上げから、ともに。</span></div><div className="ds-people-grid"><article className="ds-leader"><span className="ds-person-name">須賀<span>SUGA</span></span><div><p className="ds-kicker">GROUP LEADER</p><h3>グループ代表</h3><p>有機化学・計算化学・量子化学・高分子科学。</p><details><summary>プロフィールについて <span>＋</span></summary><p>正式な氏名表記、所属、職位、略歴は準備中です。</p></details></div></article><article className="ds-members"><p className="ds-kicker">A GROUP IN THE MAKING</p><h3>ここから、研究室をつくる。</h3><p>これから加わるメンバーの研究テーマや活動を、この場所で紹介していきます。</p><a href="#join" className="ds-link">学生の皆さんへ <span>↗</span></a></article></div></section>}
function Works({selected=false}:{selected?:boolean}){return selected?<SelectedPublications/>:<LegacyWorks/>}
function LegacyWorks(){return <section id="works" className="ds-section ds-works"><div className="ds-section-head"><p>03 / PUBLICATIONS</p><h2>論文・研究実績</h2><span>発表した研究を、正確に伝える。</span></div><div className="ds-work-table"><div><span>SELECTED PAPERS</span><h3>代表論文</h3><p>公開準備中。正式な書誌情報と研究概要を掲載します。</p></div><div><span>PROJECTS & TALKS</span><h3>プロジェクト・学会発表</h3><p>研究活動にあわせて、取り組みと成果を紹介します。</p></div></div></section>}
function Join(){return <section id="join" className="ds-section ds-join"><div className="ds-join-intro"><p className="ds-kicker">04 / JOIN THE GROUP</p><h2>分子を考えることから、<br />研究を始めよう。</h2><p>有機化学の「なぜ」に関心がある。計算を通じて分子を理解したい。新しい高分子の可能性を探りたい。そんな関心から、須賀グループの研究に触れてみてください。</p><a href="#contact" className="ds-link">見学・進学の相談について <span>↗</span></a></div><div className="ds-join-guide"><details><summary><span>01</span> どんな分野に取り組みますか？<b>＋</b></summary><p>有機化学・計算化学・量子化学・高分子科学を研究領域に、化学空間、分子探索、基礎有機化学を主なキーワードとしています。</p></details><details><summary><span>02</span> 研究室の雰囲気を知りたい<b>＋</b></summary><p>現在は立ち上げ段階です。研究環境や日々の活動は、準備が整い次第紹介します。</p></details><details><summary><span>03</span> 配属・進学の情報はありますか？<b>＋</b></summary><p>募集対象、入試・配属の手続き、相談窓口は未確定です。正式な案内を公開後にご確認ください。</p></details></div></section>}
function Collaboration({selected=false}:{selected?:boolean}){if(selected)return <CollaborationGuide/>;return <section id="collaborate" className="ds-section ds-collaboration"><p className="ds-kicker">05 / COLLABORATION</p><div><h2>分子の問いを、<br />一緒に考える。</h2><p>化学空間の探索、分子の電子状態、構造と性質の関係。異なる視点や手法が交わるところに、新しい研究の接点を探します。</p><a href="#contact" className="ds-link">共同研究の相談について <span>↗</span></a></div></section>}
function Contact(){return <section id="contact" className="ds-section ds-contact"><p className="ds-kicker">CONTACT / ACCESS</p><div><h2>須賀グループ</h2><p>所属・所在地・連絡先は準備中です。<br />共同研究・研究室見学の窓口は、確定後にご案内します。</p></div></section>}
function News({selected=false}:{selected?:boolean}){if(selected)return <GroupNews/>;return <section className="ds-news"><p className="ds-kicker">FROM THE GROUP</p><h2>研究室から</h2><div><span>STARTING UP</span><p>須賀グループは、研究室の立ち上げを進めています。</p><a href="#people" aria-label="立ち上げ中のグループを知る">↗</a></div><div><span>RESEARCH</span><p>有機化学・計算化学・量子化学・高分子科学を研究の軸に。</p><a href="#research" aria-label="研究分野を知る">↗</a></div></section>}
function SubjectLine(){return <div className="ds-subject-line"><span>有機化学</span><span>計算化学</span><span>量子化学</span><span>高分子科学</span></div>}
function Hero({slug}:{slug:StudySlug}){
 if(slug==='folio')return <section className="folio-hero"><div className="folio-stage"><div className="folio-mast"><p>SUGA GROUP / ORGANIC & COMPUTATIONAL CHEMISTRY</p><h1>Beyond<br /><i>the familiar.</i></h1><span>想像の向こうに、分子は広がる。</span></div><div className="folio-entity"><ChemicalVoyage theme="silver" speed={2.5}/></div></div><div className="folio-cover"><span className="folio-margin">THE UNKNOWN</span><div className="folio-intro"><h2>人の想像の先にある分子を、探しにいく。</h2><p>{groupIntroduction}</p></div><a href="#research" className="ds-link">研究の問いへ <span>↘</span></a></div></section>;
 if(slug==='index')return <section className="index-hero"><p className="ds-kicker">SUGA GROUP / AT THE EDGE OF DISCOVERY</p><div className="index-space"><ChemicalVoyage theme="red"/></div><div className="index-name"><h1>SINGU<br /><i>LARITY.</i></h1><span className="index-big-arrow" aria-hidden="true">↗</span></div><div className="index-intro-row"><h2>分子を知る。<br />既知を、越える。</h2><p>有機化学・計算化学・量子化学・高分子科学。化学空間と分子探索、基礎有機化学に取り組む須賀グループ。</p><a href="#research" className="ds-link">ENTER RESEARCH ↘</a></div><SubjectLine/></section>;
 if(slug==='specimen')return <section className="specimen-hero"><div className="specimen-heading"><p>SUGA GROUP / XENOCHEMISTRY</p><h1>まだ、名前のない<br /><i>可能性。</i></h1><div><span>EXHIBIT / 001</span><p>分子の構造を見つめる。<br />人間の想像の、その先まで。</p></div><a href="#research" className="ds-link">研究領域を探索する ↘</a></div><figure className="specimen-plate"><div className="plate-label"><b>SG—001</b><span>BEYOND KNOWN STRUCTURES</span></div><ChemicalVoyage theme="white"/><figcaption><b>01</b><div>THE UNFAMILIAR<small>可能性の広がりを表現した模式映像</small></div><a href="#research" aria-label="研究領域を見る">↗</a></figcaption></figure></section>;
 if(slug==='ledger')return <section className="ledger-hero"><div className="ledger-issue"><span>SUGA GROUP / LATENT SPACE</span><span>MOLECULAR EXPLORATION</span><span>VIEW / 001</span></div><div className="ledger-headline"><div><p className="ds-kicker">THE UNSEEN POSSIBILITIES</p><h1>Not yet<br /><em>imagined.</em></h1><h2>探索の先で、<br />予期しない分子に出会う。</h2><p>化学空間を探り、分子を理解する。<br />有機化学と計算のあいだに、新しい発見を。</p><a href="#research" className="ds-link">探索の問いを知る ↘</a></div><div className="ledger-voyage"><ChemicalVoyage theme="green"/></div></div><SubjectLine/></section>;
 return <section className="aperture-hero"><div className="aperture-copy"><p className="ds-kicker">SUGA GROUP / BEYOND THE VISIBLE</p><h1>The edge<br /><i>of knowing.</i></h1><h2>その先は、<br />まだ見えない。</h2><p>有機化学・計算化学・量子化学・高分子科学。化学空間の探索から、分子のふるまいの理解へ。</p><a href="#research" className="ds-link">境界の先へ <span>↘</span></a></div><div className="aperture-voyage"><ChemicalVoyage theme="blue"/></div></section>;
}export function DesignPage({slug,selected=false}:{slug:StudySlug;selected?:boolean}){const study=studies.find(s=>s.slug===slug)!;return <div className={`ds ds-${slug}${selected ? " ds-current" : ""}`}><a href="#main" className="ds-skip">本文へ移動</a>{!selected && <div className="ds-review"><a href="/designs">← 5案を比較</a><nav aria-label="デザイン比較">{studies.map(s=><a href={`/directions/${s.slug}`} key={s.id} aria-current={s.slug===slug?'page':undefined}>{s.id}<span> {s.name}</span></a>)}</nav><span>第3稿 / デザイン案</span></div>}<div className="ds-frame">{selected ? <GroupHeader/> : <header className="ds-header"><a href="#top" className="ds-brand">須賀グループ<small>SUGA GROUP</small></a><nav aria-label="研究室ナビゲーション">{menu.map(([id,label],i)=><a key={id} href={`#${id}`}><span>{String(i+1).padStart(2,'0')}</span>{label}</a>)}<a href="#contact"><span>06</span>お問い合わせ</a></nav></header>}<main id="main"><div id="top"><Hero slug={slug}/></div><div className="ds-body">{slug==='folio'?<><News selected={selected}/><Research selected={selected}/><People selected={selected}/><Works selected={selected}/>{selected ? <StudentGuide/> : <Join/>}<Collaboration selected={selected}/></>:slug==='index'?<><Research selected={selected}/><News selected={selected}/><Works selected={selected}/><People selected={selected}/><Collaboration selected={selected}/>{selected ? <StudentGuide/> : <Join/>}</>:slug==='specimen'?<><Research selected={selected}/><People selected={selected}/><Works selected={selected}/><News selected={selected}/><Collaboration selected={selected}/>{selected ? <StudentGuide/> : <Join/>}</>:slug==='ledger'?<><div className="ledger-opening"><News selected={selected}/><aside><p className="ds-kicker">UNEXPLORED</p><h2>どんな分子が、<br />まだ見つかっていない？</h2><a href="#research" className="ds-link">研究の問いへ ↗</a></aside></div><People selected={selected}/><Research selected={selected}/>{selected ? <StudentGuide/> : <Join/>}<Works selected={selected}/><Collaboration selected={selected}/></>:<><SubjectLine/><Research selected={selected}/><Collaboration selected={selected}/><Works selected={selected}/><People selected={selected}/><News selected={selected}/>{selected ? <StudentGuide/> : <Join/>}</>}{selected ? <GroupContact/> : <Contact/>}</div></main></div><footer className="ds-footer"><div><a href="#top">SUGA GROUP ↑</a><span>有機化学 / 計算化学 / 量子化学 / 高分子科学</span></div><p>{selected ? "© SUGA GROUP" : `DESIGN ${study.id} — ${study.name}`} · {selected ? "映像は化学空間の模式表現です。" : "映像・図は化学空間の模式表現です。研究文章は仮案です。正式な情報は確定後に更新します。"}</p></footer></div>}
